site_name: Web labs reports

nav:
  - Home: index.md
  - Lab-2:
    - Task 1: task1.md
    - Task 2: task2.md

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
